from __future__ import annotations

AK_OK = 0

AK_FILE_TYPE_AUTO = 0
AK_FILE_TYPE_COLLADA = 1
AK_FILE_TYPE_DAE = AK_FILE_TYPE_COLLADA
AK_FILE_TYPE_GLTF = 2
AK_FILE_TYPE_WAVEFRONT = 3
AK_FILE_TYPE_OBJ = AK_FILE_TYPE_WAVEFRONT
AK_FILE_TYPE_STL = 4
AK_FILE_TYPE_PLY = 5
AK_FILE_TYPE_3MF = 6
AK_FILE_TYPE_X3D = 7
AK_FILE_TYPE_USD = 8
AK_FILE_TYPE_ALEMBIC = 9
AK_FILE_TYPE_GLB = 10

AK_DAE_EXPORT_INDEX_MULTI = 0
AK_DAE_EXPORT_INDEX_SINGLE = 1
AK_DAE_EXPORT_INDEX_AUTO = 2

AK_DAE_EXPORT_VERSION_AUTO = 0
AK_DAE_EXPORT_VERSION_1_4 = 1
AK_DAE_EXPORT_VERSION_1_5 = 2

AK_GLTF_EXPORT_VERSION_AUTO = 0
AK_GLTF_EXPORT_VERSION_2_0 = 1
AK_GLTF_EXPORT_VERSION_2_1 = 2

AK_STL_EXPORT_BINARY = 0
AK_STL_EXPORT_ASCII = 1
AK_PLY_EXPORT_BINARY_LITTLE = 0
AK_PLY_EXPORT_ASCII = 1
AK_PLY_EXPORT_COLOR_NONE = 0
AK_PLY_EXPORT_COLOR_SRGB = 1
AK_PLY_EXPORT_COLOR_LINEAR = 2

AK_GEOMETRY_MESH = 1

AK_PRIMITIVE_LINES = 1
AK_PRIMITIVE_POLYGONS = 2
AK_PRIMITIVE_TRIANGLES = 3
AK_PRIMITIVE_POINTS = 4

AK_INPUT_COLOR = 2
AK_INPUT_JOINT = 9
AK_INPUT_NORMAL = 13
AK_INPUT_POSITION = 16
AK_INPUT_TANGENT = 17
AK_INPUT_TEXCOORD = 19
AK_INPUT_UV = 21
AK_INPUT_WEIGHT = 22

AK_PROJECTION_PERSPECTIVE = 0
AK_PROJECTION_ORTHOGRAPHIC = 1

AK_LIGHT_TYPE_DIRECTIONAL = 2
AK_LIGHT_TYPE_POINT = 3
AK_LIGHT_TYPE_SPOT = 4

AK_TARGET_POSITION = 7
AK_TARGET_SCALE = 8
AK_TARGET_QUAT = 10
AK_TARGET_WEIGHTS = 11

AKB_ANIM_VISIBILITY = 5
AKB_ANIM_MATERIAL_BASE_COLOR = 32
AKB_ANIM_MATERIAL_METALLIC = 33
AKB_ANIM_MATERIAL_ROUGHNESS = 34
AKB_ANIM_MATERIAL_ALPHA_CUTOFF = 35
AKB_ANIM_MATERIAL_EMISSIVE_COLOR = 36
AKB_ANIM_MATERIAL_EMISSIVE_STRENGTH = 37
AKB_ANIM_MATERIAL_NORMAL_SCALE = 38
AKB_ANIM_MATERIAL_OCCLUSION_STRENGTH = 39
AKB_ANIM_MATERIAL_SPECULAR = 40
AKB_ANIM_MATERIAL_SPECULAR_COLOR = 41
AKB_ANIM_MATERIAL_IOR = 42
AKB_ANIM_MATERIAL_CLEARCOAT = 43
AKB_ANIM_MATERIAL_CLEARCOAT_ROUGHNESS = 44
AKB_ANIM_MATERIAL_CLEARCOAT_NORMAL_SCALE = 45
AKB_ANIM_MATERIAL_TRANSMISSION = 46
AKB_ANIM_MATERIAL_SHEEN_COLOR = 47
AKB_ANIM_MATERIAL_SHEEN_ROUGHNESS = 48
AKB_ANIM_MATERIAL_IRIDESCENCE = 49
AKB_ANIM_MATERIAL_IRIDESCENCE_IOR = 50
AKB_ANIM_MATERIAL_IRIDESCENCE_THICKNESS_MINIMUM = 51
AKB_ANIM_MATERIAL_IRIDESCENCE_THICKNESS_MAXIMUM = 52
AKB_ANIM_MATERIAL_VOLUME_THICKNESS = 53
AKB_ANIM_MATERIAL_VOLUME_ATTENUATION_DISTANCE = 54
AKB_ANIM_MATERIAL_VOLUME_ATTENUATION_COLOR = 55
AKB_ANIM_MATERIAL_ANISOTROPY = 56
AKB_ANIM_MATERIAL_ANISOTROPY_ROTATION = 57
AKB_ANIM_MATERIAL_DISPERSION = 58
AKB_ANIM_MATERIAL_DIFFUSE_TRANSMISSION = 59
AKB_ANIM_MATERIAL_DIFFUSE_TRANSMISSION_COLOR = 60

AK_INTERPOLATION_LINEAR = 1
AK_INTERPOLATION_STEP = 6

AKB_EXPORT_ITEM_NODE = 0
AKB_EXPORT_ITEM_MESH = 1
AKB_EXPORT_ITEM_CAMERA = 2
AKB_EXPORT_ITEM_LIGHT = 3
AKB_EXPORT_ITEM_JOINT = 4
AKB_EXPORT_ITEM_CURVE = 5

AKB_LOAD_OPT_COORD_SYSTEM = 0
AKB_LOAD_OPT_COORD_CONVERSION = 1
AKB_LOAD_OPT_SCENE_INDEX = 2
AKB_LOAD_OPT_TRIANGULATE = 3
AKB_LOAD_OPT_GENERATE_NORMALS = 4
AKB_LOAD_OPT_CONVERT_TRIANGLE_STRIP = 5
AKB_LOAD_OPT_CONVERT_TRIANGLE_FAN = 6
AKB_LOAD_OPT_IMPORT_LINES = 7
AKB_LOAD_OPT_CONVERT_LINE_LOOP = 8
AKB_LOAD_OPT_CONVERT_LINE_STRIP = 9
AKB_LOAD_OPT_USE_MMAP = 10
AKB_LOAD_OPT_PRESERVE_EXTRAS = 11
AKB_LOAD_OPT_BUILD_TRIANGLE_EDGES = 12
AKB_LOAD_OPT_GEOMETRY_KEYS = 13
AKB_LOAD_OPT_GEOMETRY_CONTENT_KEYS = 14
AKB_LOAD_OPT_TEXTURE_LOADING = 15
AKB_LOAD_OPT_DEFER_CUSTOM_NORMALS = 16
AKB_LOAD_OPT_PRESERVE_TANGENTS = 17
AKB_LOAD_OPT_COUNT = 18

AKB_LOAD_COORD_Z_UP = 0
AKB_LOAD_COORD_Y_UP = 1
AKB_LOAD_COORD_X_UP = 2
AKB_LOAD_COORD_Z_UP_LH = 3
AKB_LOAD_COORD_Y_UP_LH = 4
AKB_LOAD_COORD_X_UP_LH = 5

AKB_LOAD_COORD_RAW = 0
AKB_LOAD_COORD_TRANSFORM = 1
AKB_LOAD_COORD_ALL = 2

AKB_LOAD_TEXTURE_AUTO = 0
AKB_LOAD_TEXTURE_IMMEDIATE = 1
AKB_LOAD_TEXTURE_DEFERRED = 2

AKB_LOAD_DEFER_NORMALS_AUTO = 0
AKB_LOAD_DEFER_NORMALS_NO = 1
AKB_LOAD_DEFER_NORMALS_YES = 2

AKT_FLOAT = 10
AKT_DOUBLE = 33
AKT_INT = 6
AKT_UINT = 28
AKT_HALF = 69
AKT_BYTE = 29
AKT_UBYTE = 30
AKT_SHORT = 31
AKT_USHORT = 32
AKT_INT64 = 34
AKT_UINT64 = 35

__all__ = tuple(name for name in globals() if name.startswith(("AK_", "AKB_", "AKT_")))
